DROP TABLE IF EXISTS ROLES_USUARIO;
DROP TABLE IF EXISTS ROLES;
DROP TABLE IF EXISTS COMENTARIOS_FORO;
DROP TABLE IF EXISTS RESENA;
DROP TABLE IF EXISTS SERVICIOS_CONTRATADOS;
DROP TABLE IF EXISTS SERVICIOS_FAVORITOS;
DROP TABLE IF EXISTS ESTADO_SERVICIOS;
DROP TABLE IF EXISTS MENSAJES;
DROP TABLE IF EXISTS ESTADO_MENSAJES;
DROP TABLE IF EXISTS USUARIOS;
DROP TABLE IF EXISTS SERVICIO;
DROP TABLE IF EXISTS FORO;
DROP TABLE IF EXISTS CATEGORIA_SERVICIOS;
DROP TABLE IF EXISTS CONVERSACIONES;

CREATE TABLE IF NOT EXISTS ROLES (
  ID int(11) NOT NULL AUTO_INCREMENT,
  NOMBRE varchar(15) COLLATE utf8mb4_general_ci NOT NULL,
  PRIMARY KEY (ID)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS ROLES_USUARIO (
  USUARIO int(11) NOT NULL,
  ROL int(11) NOT NULL,
  PRIMARY KEY (USUARIO,ROL),
  KEY ROL (ROL)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;


CREATE TABLE IF NOT EXISTS USUARIOS (
    ID                 int(11)                                  NOT NULL,
    USERNAME           varchar(30) COLLATE utf8mb4_general_ci   NOT NULL,
    PASSWORD           varchar(70) COLLATE utf8mb4_general_ci   NOT NULL,
    EMAIL               VARCHAR(100) 	                        NOT NULL,
    TELEFONO            INT 		   	                        NOT NULL,
    SALDO_MONEDERO      INT                                     NOT NULL,
    FECHA_CREACION      DATE                                    NOT NULL,
    NOMBRE              VARCHAR(50)  	                        NOT NULL,
    APELLIDO1           VARCHAR(50)  	                        NOT NULL,
    APELLIDO2           VARCHAR(50)  	                        NULL,
    FECHA_NACIMIENTO    DATE                                    NOT NULL,
    IMAGEN              VARCHAR(250)                            NULL,
    SERVICIO_OFERTADO   INT                                     NULL,
    DESCRIPCION         VARCHAR(250)                            NULL,			   	
    PAIS                VARCHAR(50)  	                        NULL,
    CIUDAD              VARCHAR(50)                             NULL,
    CALLE               VARCHAR(75)  	                        NULL,
    NUMERO_CALLE        VARCHAR(10)                             NULL,
    PORTAL 				VARCHAR(6)   	                        NULL,
    PISO 				VARCHAR(12)  	                        NULL,
    PUERTA 				VARCHAR(10)                             NULL,
    CODIGO_POSTAL 		VARCHAR(5)   	                        NULL
) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE SERVICIO(
    ID                  INT             NOT NULL,
    TITULO              VARCHAR(250)    NOT NULL,
    COSTE               INT			    NOT NULL,
    CATEGORIA_SERVICIOS INT             NOT NULL,
    DESCRIPCION         VARCHAR(250)    NOT NULL,
    IMAGEN              VARCHAR(250)    NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE FORO(
    ID                  INT             NOT NULL,
    TEMA_FOROS          INT             NOT NULL,
    ASUNTO              VARCHAR(100)    NOT NULL  
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE COMENTARIOS_FORO(
    ID                  INT             NOT NULL,
    FORO                INT             NOT NULL,
    CONTENIDO           VARCHAR(300)    NOT NULL,
    USUARIO_CREADOR     INT             NOT NULL,
    FECHA_CREACION      DATETIME        NOT NULL,
    ID_PADRE            INT             DEFAULT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE RESENA(
    ID                 INT              NOT NULL,
    USUARIO_CREADOR    INT              NOT NULL,
    USUARIO_VALORADO   INT              NOT NULL,
    PUNTUACION         INT              NOT NULL,
    COMENTARIO         VARCHAR(300)     NOT NULL,
    FECHA_VALORACION   DATE             NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE SERVICIOS_CONTRATADOS(
    ID                   INT            NOT NULL,
    USUARIO_CONTRATADOR  INT            NOT NULL,
    USUARIO_REALIZADOR   INT            NOT NULL,
    SERVICIO             INT            NOT NULL,
    FECHA_SOLICITUD      DATETIME           NULL,
    FECHA_REALIZACION    DATETIME           NULL,
    FECHA_FINALIZACION   DATETIME           NULL,
    ESTADO               INT            NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS SERVICIOS_FAVORITOS(
    USUARIO                     INT          NOT NULL,
    SERVICIO                    INT          NOT NULL,
    PRIMARY KEY (USUARIO, SERVICIO),
    KEY SERVICIO (SERVICIO)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE CATEGORIA_SERVICIOS(
    ID                          INT          NOT NULL,
    NOMBRE                      VARCHAR(50)  NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE ESTADO_SERVICIOS(
    ID                          INT          NOT NULL,
    NOMBRE                      VARCHAR(50)  NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE CONVERSACIONES(
    ID                      INT              NOT NULL,
    USUARIO1                 INT              NOT NULL,
    USUARIO2                 INT              NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
    
CREATE TABLE MENSAJES(
    ID                INT             NOT NULL,
    CONVERSACION      INT             NOT NULL,
    AUTOR             INT             NOT NULL,
    CONTENIDO         VARCHAR(130)    NOT NULL,
    FECHA_HORA        DATETIME        NOT NULL,
    ESTADO            INT             NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE ESTADO_MENSAJES(
    ID                          INT          NOT NULL,
    NOMBRE                      VARCHAR(50)  NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

ALTER TABLE USUARIOS                ADD CONSTRAINT USUARIOS_PK                                  PRIMARY KEY (ID);
ALTER TABLE SERVICIO                ADD CONSTRAINT SERVICIO_PK                                  PRIMARY KEY (ID);
ALTER TABLE FORO                    ADD CONSTRAINT FORO_PK                                      PRIMARY KEY (ID);
ALTER TABLE COMENTARIOS_FORO        ADD CONSTRAINT COMENTARIOS_FORO_PK                          PRIMARY KEY (ID);
ALTER TABLE RESENA                  ADD CONSTRAINT RESENA_PK                                    PRIMARY KEY (ID);
ALTER TABLE SERVICIOS_CONTRATADOS   ADD CONSTRAINT SERVICIOS_CONTRATADOS_PK                     PRIMARY KEY (ID);
ALTER TABLE ESTADO_SERVICIOS        ADD CONSTRAINT ESTADO_SERVICIOS_PK                          PRIMARY KEY (ID);
ALTER TABLE ESTADO_MENSAJES         ADD CONSTRAINT ESTADO_MENSAJES_PK                           PRIMARY KEY (ID);
ALTER TABLE CATEGORIA_SERVICIOS     ADD CONSTRAINT CATEGORIA_SERVICIOS_PK                       PRIMARY KEY (ID);
ALTER TABLE MENSAJES                ADD CONSTRAINT MENSAJES_PK                                  PRIMARY KEY (ID);
ALTER TABLE CONVERSACIONES          ADD CONSTRAINT CONVERSACIONES_PK                            PRIMARY KEY (ID, USUARIO1, USUARIO2);

ALTER TABLE USUARIOS                ADD CONSTRAINT USUARIOS_EMAIL_UQ                            UNIQUE (EMAIL);
ALTER TABLE USUARIOS                ADD CONSTRAINT USUARIOS__USERNAME_UQ                        UNIQUE (USERNAME);
ALTER TABLE CATEGORIA_SERVICIOS     ADD CONSTRAINT CATEGORIA_SERVICIOS_NOMBRE_UQ                UNIQUE (NOMBRE);

ALTER TABLE ROLES_USUARIO           ADD CONSTRAINT ROLES_USUARIO_USUARIO_FK                     FOREIGN KEY (USUARIO)                    REFERENCES USUARIOS (ID)                  ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE ROLES_USUARIO           ADD CONSTRAINT ROLES_USUARIO_ROL_FK                         FOREIGN KEY (ROL)                        REFERENCES ROLES (ID)                     ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE SERVICIO                ADD CONSTRAINT SERVICIO_CATEGORIA_SERVICIOS_FK              FOREIGN KEY (CATEGORIA_SERVICIOS)         REFERENCES CATEGORIA_SERVICIOS(ID)        ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE FORO                    ADD CONSTRAINT FORO_TEMA_FOROS_FK                           FOREIGN KEY (TEMA_FOROS)                  REFERENCES CATEGORIA_SERVICIOS(ID)        ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE COMENTARIOS_FORO        ADD CONSTRAINT COMENTARIOS_FORO_FORO_FK                     FOREIGN KEY (FORO)                        REFERENCES FORO(ID)                       ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE COMENTARIOS_FORO        ADD CONSTRAINT COMENTARIOS_FORO_USUARIO_CREADOR_FK          FOREIGN KEY (USUARIO_CREADOR)            REFERENCES USUARIOS(ID)                   ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE COMENTARIOS_FORO        ADD CONSTRAINT COMENTARIOS_FORO_ID_PADRE_FK                 FOREIGN KEY (ID_PADRE)                   REFERENCES COMENTARIOS_FORO(ID)           ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE RESENA                  ADD CONSTRAINT RESENA_USUARIO_CREADOR_FK                    FOREIGN KEY (USUARIO_CREADOR)            REFERENCES USUARIOS(ID)                   ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE RESENA                  ADD CONSTRAINT RESENA_USUARIO_VALORADO_FK                   FOREIGN KEY (USUARIO_VALORADO)           REFERENCES USUARIOS(ID)                   ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE SERVICIOS_CONTRATADOS   ADD CONSTRAINT SERVICIOS_CONTRATADOS_USUARIO_CONTRATADOR_FK FOREIGN KEY (USUARIO_CONTRATADOR)        REFERENCES USUARIOS(ID)                   ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE SERVICIOS_CONTRATADOS   ADD CONSTRAINT SERVICIOS_CONTRATADOS_USUARIO_REALIZADOR_FK  FOREIGN KEY (USUARIO_REALIZADOR)         REFERENCES USUARIOS(ID)                   ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE SERVICIOS_CONTRATADOS   ADD CONSTRAINT SERVICIOS_CONTRATADOS_SERVICIO_FK            FOREIGN KEY (SERVICIO)                   REFERENCES SERVICIO(ID)                   ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE SERVICIOS_CONTRATADOS   ADD CONSTRAINT SERVICIOS_CONTRATADOS_ESTADO_FK              FOREIGN KEY (ESTADO)                     REFERENCES ESTADO_SERVICIOS(ID)           ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE SERVICIOS_FAVORITOS     ADD CONSTRAINT SERVICIOS_FAVORITOS_USUARIO_FK               FOREIGN KEY (USUARIO)                    REFERENCES USUARIOS(ID)                   ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE SERVICIOS_FAVORITOS     ADD CONSTRAINT SERVICIOS_FAVORITOS_SERVICIO_FK              FOREIGN KEY (SERVICIO)                   REFERENCES SERVICIO(ID)                   ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE CONVERSACIONES          ADD CONSTRAINT CONVERSACIONES_USUARIO1_FK                   FOREIGN KEY (USUARIO1)                   REFERENCES USUARIOS(ID)                   ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE CONVERSACIONES          ADD CONSTRAINT CONVERSACIONES_USUARIO2_FK                   FOREIGN KEY (USUARIO2)                   REFERENCES USUARIOS(ID)                   ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE MENSAJES                ADD CONSTRAINT MENSAJES_AUTOR_FK                            FOREIGN KEY (AUTOR)                      REFERENCES USUARIOS(ID)                   ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE MENSAJES                ADD CONSTRAINT MENSAJES_CONVERSACION_FK                     FOREIGN KEY (CONVERSACION)               REFERENCES CONVERSACIONES(ID)             ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE MENSAJES                ADD CONSTRAINT MENSAJES_ESTADO_FK                           FOREIGN KEY (ESTADO)                     REFERENCES ESTADO_MENSAJES(ID)            ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE USUARIOS                MODIFY ID INT NOT NULL AUTO_INCREMENT;
ALTER TABLE SERVICIO                MODIFY ID INT NOT NULL AUTO_INCREMENT;
ALTER TABLE FORO                    MODIFY ID INT NOT NULL AUTO_INCREMENT;
ALTER TABLE COMENTARIOS_FORO        MODIFY ID INT NOT NULL AUTO_INCREMENT;
ALTER TABLE RESENA                  MODIFY ID INT NOT NULL AUTO_INCREMENT;
ALTER TABLE SERVICIOS_CONTRATADOS   MODIFY ID INT NOT NULL AUTO_INCREMENT;
ALTER TABLE CATEGORIA_SERVICIOS     MODIFY ID INT NOT NULL AUTO_INCREMENT;
ALTER TABLE MENSAJES                MODIFY ID INT NOT NULL AUTO_INCREMENT;
ALTER TABLE CONVERSACIONES          MODIFY ID INT NOT NULL AUTO_INCREMENT;


